source 'https://rubygems.org'

#Core Libraries

gem 'rails', '4.1.6'
gem 'sqlite3'
gem 'pry-rails'
gem 'annotate'

#Front End Libraries
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'spring',        group: :development

#Debugging and Testing Libraries
gem 'better_errors'
gem 'binding_of_caller'
gem 'pry'
gem 'pry-byebug'



gem 'sdoc', '~> 0.4.0',          group: :doc